aws_account: "637423239508"
aws_region: us-east-1

network:
  vpc:
    cidr: 10.50.0.0/16


compute:
  batchjob:
    env:
      USER_SCRIPTS_BUCKET_NAME: jkpfactors-user-scripts
      INTEGRITY_CHECK_DATA_S3_URI: "s3://jkpfactors-training-data/integrity-check/"
      INTEGRITY_CHECK_DATA_LOCAL_PATH: "integrity-check/"
      COMPLETE_DATA_S3_URI: "s3://jkpfactors-training-data/complete/"
      COMPLETE_DATA_PATH: "data/"
      SHOULD_PERFORM_COMPLETE_TRAINING: "True"
      SHOULD_PERFORM_INTEGRITY_CHECK: "True"


storage:
  s3:
    scripts_upload_bucket: jkpfactors-user-scripts-dev
    trainings_data_bucket: jkpfactors-training-data
    ml_batch_jobs_bucket: jkpfactors-ml-batch-jobs-dev

  db:
    benchmarks_table: benchmarks
    submissions_table: submissions