aws_account: "637423239508"
aws_region: us-east-1

network:
  vpc:
    cidr: 10.50.0.0/16

storage:
  s3:
    scripts_upload_bucket: jkpfactors-user-scripts-dev
    trainings_data_bucket: jkpfactors-training-data
    ml_batch_jobs_bucket: jkpfactors-ml-batch-jobs-dev

  db:
    benchmarks_table: benchmarks
    submissions_table: submissions